### ISSUE TITLE
Licensing issue?

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#210]
I'm not a lawyer and probably make mistakes here but in my opinion your "Custom ISC License" is not a good idea. The custom license isn't even near the original ISC License in terms of restrictions/freedom to be called like that. Your license is a non-free software license because you don't mention "copying and distributing" and it restricts the use and modification of the application if someone or something (not specified in the license) doesn't commit "any work" to upstream. Doesn't the terms also restricts the user to get a copy of it?

I scanned the contributing guidelines and didn't find something about licensing there. Wouldn't it mean that contribution from other people are under your restrictive custom license too? https://docs.github.com/en/github/site-policy/github-terms-of-service If that's true you are also bound to your own custom license.

I mean if you just want other people to share their code a copyleft license like the GNU GPLv3+ would legally do it too.

**Comment by Sven792** [comment]
Interesting thought there, @lionkor . I agree with you on the AGPL part as a free software enthusiast (free as in freedom not free beer). I mentioned the GPL because I thought more about the client then the server. However, the GNU AGPL can and should be used IMO for both client and server. AGPL wouldn't make much of a difference for client-side software in comparison to the GPL (in case no one give it special networking functionality).

If I think about the monetary view: Why not promote your Patreon account? The BeamMP community already give you some love there.

If we are talking about cheaters in the game:
- You can say in your Terms of Service that you don't tolerate cheaters.
- Have server-side anti-cheat or at least some basic checks if everything is alright.
- Give players the ability to report cheaters. I mean you have an account system, right?

A software license will NOT help "against people taking the mod and modifying it to crash or otherwise disrupt other people's games, or to get a competetive [sic] advantage". There are even cheaters on proprietary and closed-source games.

**Comment by lionkor** [comment]
> A software license will NOT help "against people taking the mod and modifying it to crash or otherwise disrupt other people's games, or to get a competetive [sic] advantage". There are even cheaters on proprietary and closed-source games.

That's actually fair, yeah, dismiss my point about that

**Comment by Nevin1901** [comment]
I think the license should be made as free as possible. I doubt license or Open Source Code affects sales in any way. I run a business which I plan to open source, and I still make money.

I highly doubt cheaters would abide by any TOS/Open Source License when developing things to crash other people's games. if the code was closed source they would just reverse it.

This project not being open source helps no one. I suggest that the developers stop hiding behind the fear that "someone will steal my work or break the game", and just look at the current facts. The code has been available to view. Has a copycat project started? no. Have cheaters broken the game beyond repair? no.

Quite honestly if the beamMP team wanted to make money they should provide easy server hosting for $$ (nice web gui). I'm sure they could even open source THAT project, and still get people who would love to pay them for the convenience.

**Comment by lionkor** [comment]
> which I plan to open source

There is a difference between planning to do it, doing it, and actually being successful doing it. I'd love to talk to people who have successfully taken a project like this open source and still were able to pay for their infrastructure, but I sadly don't have contact to any.

> hiding behind the fear

While I understand what you're trying to say, please understand that some of us work almost exclusively on FOSS projects (see my github and gitlab, for example). We *understand* the value of open source software, and the challenges, too. There are a number of things that *could* happen once we're open source, that *cannot* happen while we're source-available. This includes, for example, any other company, whether BeamNG related or not, taking and using our code with little to no value added to the project.

Of course you can take the BeamMP code, put some hacks in there, make it really unfair, but at least you can't post it on the BeamNG forums or sell it openly. If it was open source, you could.

This is not fear, it's caution.

> Has a copycat project started?

We had copycat projects before, who tried to take heavy inspiration from the way we implemented multiplayer. It would not have benefitted us, at the time, to open source it.

> This project not being open source helps no one

I agree that open sourcing the mod itself, for example, would add some value. There are probably a handful of people in the community with the time, lua knowlegde, *and* interest to contribute, who aren't already part of our team. I would have hoped for more of them to share their point of view in this thread.

**Comment by Sven792** [comment]
> I suggest that the developers stop hiding behind the fear that "someone will steal my work or break the game", and just look at the current facts. 

You can't steal something that is available free of charge like the source code here. How do you pirate information? I mean I can pirate your ship if you have one. arrrr :D
It could be unauthorized copying, modifying and/or distributing under the copyright law and nothing more.

It's also false to see their view as fear. They probably have a goal and decided based on how they think it fits the most. It's their project and not yours in the end.

> This includes, for example, any other company, whether BeamNG related or not, taking and using our code with little to no value added to the project.

Depending on what you want to achieve the GNU Affero General Public License version 3 or newer can be useful for client and even for servers because it somehow covers networking too.

> Of course you can take the BeamMP code, put some hacks in there, make it really unfair, but at least you can't post it on the BeamNG forums or sell it openly. If it was open source, you could.

There are rules of the BeamNG forums that could be interpreted to your advantage even if your software is free/libre. I think it's better to talk with the forum moderators about this specific issue however.
And selling cheats under e.g. the GNU (A)GPL doesn't make much sense for cheat developers (if they do it legally).
