### ISSUE TITLE
[Bug] Invalid `Oc` packet sent every ~15 seconds

### ISSUE THREAD

**Issue by lionkor** [Starystars67/BeamNG-MP#269]
**Describe the bug**
On some occasions, the client sends (every ~15 seconds or so), an `Oc` packet for another player. This isn't right, and @snepsnepsnep confirmed this is likely a client side bug that we've seen before.

The server obviously doesn't accept these packets, but they are in the neighborhood of 5kB each, and cause a big strain on the network.

I attached a log, it's from the official development server, which runs v3.1.0 (unrelated). I've redacted most of their name, just in case, but it's the guy called `Ra*****oy`. **Log: [Ra_oy.log](https://github.com/BeamMP/BeamMP/files/9815145/Ra_oy.log)**

**To Reproduce**
TODO? No idea.

Screenshot, illustrated in RED: timestamp (not far apart), in GREEN: differing player ids, in YELLOW: differing jbm's (of course):
![image](https://user-images.githubusercontent.com/29932116/196545905-bfb052c3-52b4-4044-a2d9-c06a95e264fd.png)

**Comment by snepsnepsnep** [comment]
It seems to be caused by having the "Enable auto part sync" option enabled, which sends your own vehicle config data 15 seconds after the last modification, and `sendVehicleEdit` lacks a check for if the vehicle modified is your own so it ends up sending it 15 seconds after other people's vehicle have been modified too.
Imo we should just immediately send all config updates and queue them on the receiving side instead (maybe add extra logic for just vehicle modifications to the current queue system).
