### ISSUE TITLE
[Bug] MPGameNetwork attempts to index a function

### ISSUE THREAD

**Issue by 5TXdYWK** [Starystars67/BeamNG-MP#388]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
![image](https://github.com/BeamMP/BeamMP/assets/82390521/92fdd956-b393-47f6-b6ee-12f417e2c979)

**To Reproduce**
1. Attempt to join a local BeamMP server

**Expected behavior**
I should load into the server instead of being stuck in the loading screen

**Comment by Starystars67** [comment]
Hi there, Please can you provide me with the mod version and launcher version are you using please?

**Comment by 5TXdYWK** [comment]
> Hi there, Please can you provide me with the mod version and launcher version are you using please?

@Starystars67 launcher 2.0.82; main menu reports BeamMP 4.9.3

**Comment by OfficialLambdax** [comment]
So [sendData()](https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPGameNetwork.lua#L64) was probably called because carp wanted to send event data to the server.. i take that from the screenshot. but the var TCPLauncherSocket was still [nop](https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPGameNetwork.lua#L13C7-L13C24). Hence it could not be indexed with :send().

[sendData() doesnt cover this case](https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPGameNetwork.lua#L77)
