### ISSUE TITLE
[Bug] Beamlings Customisation does not save

### ISSUE THREAD

**Issue by VanilleVaschnille** [Starystars67/BeamNG-MP#455]
**The Issue**

When selecting a customisation for the beamlings and then get into a vehicle, the character resets to default in a server with multiple unicycles.

**To Reproduce**
- Load into a server with another person and customise your character. 
- get into a vehicle and get out again.

**Expected behavior**
The characters are supposed to keep their customisation when getting in and out of vehicles.

**Additional context**
I was not there when they issues were found, these were reported by the beaming YouTube recording team.

**Comment by OfficialLambdax** [comment]
This is intented behaviour. In order to set a new default
1. you either have to save your unicycle to a config, go into the multiplayer settings, and then select that config to be your default
2. or you enable the option that autosaves your last used config everytime you despawn it and this way makes it your default

in a voting the first version overwhelmingly won, so yeah, thats just how it is intented to be

**Comment by lionkor** [comment]
I dont know who was present during this vote but I don't think it was documented. I would suggest of a complete redo of the beamlings feature, reusing code that still fits, because apparently nobody has any idea what exactly anyone else wanted here.

Lets please make an issue to redesign the beamlings code and actually specify IN WRITTEN WORDS what the acceptance criteria are, without VCs or meetings or DMs or votes in discord where its difficult to track what was decided.

**Comment by OfficialLambdax** [comment]
nothing really needs to be redone. if we want to autosave as the default funtionality, then we just have to turn a `false` to a `true` in the MPConfig.lua. The lua support just adds the ability to auto spawn a users default, the way a player tho chooses a default is clumbersome (over the multiplayer options), but it was voted that way by **everyone**.
