### ISSUE TITLE
IMPORTANT LICENSE CHANGE

### ISSUE THREAD

**Issue by lionkor** [Starystars67/BeamNG-MP#490]
Hey @Starystars67 @20dka @snepsnepsnep @jojos38 @OfficialLambdax @stefan750 @Olrosse @Please-Pick-a-Name @vulcan-dev @StanleyDudek @scisdev @O1LER @Anonymous-275 @Mack29446 @prestonelam2003 @50thomatoes50 @2PXL @AlexITA1100 @0R3Z @Desoroxxx @YumiNee213 @JamesBlad @iTeeLion @ArmenG888 @1eob @jacobcargen @5TXdYWK @daveywaveyHD @VanilleVaschnille @rtkpX @NewZulund @Neptnium @x0xDJSx0x @NicholasMcMillan03,

We're changing the license of this codebase to AGPL-3.0.

Please respond with a short "Okay" or similar message of acknowledgement. If you have any issues or concerns, please make them known.

We will move ahead with the AGPL-3.0 change, we need to know who's code we need to remove for this.

**Comment by lionkor** [comment]
This means YOUR CODE that you contributed, if it's still in the current codebase, will be relicensed under AGPL-3.0 and you formally agree to that by responding positively here.

**Comment by jojos38** [comment]
Hi Lion, would you mind explaining the reason to this change and what it will change compared to the previous licence please?
________________________________
De : Lion ***@***.***>
Envoyé : samedi 13 janvier 2024 21:41
À : BeamMP/BeamMP ***@***.***>
Cc : jojos38 ***@***.***>; Mention ***@***.***>
Objet : [BeamMP/BeamMP] IMPORTANT LICENSE CHANGE (Issue #490)


Hey @Starystars67<https://github.com/Starystars67> @20dka<https://github.com/20dka> @snepsnepsnep<https://github.com/snepsnepsnep> @jojos38<https://github.com/jojos38> @OfficialLambdax<https://github.com/OfficialLambdax> @stefan750<https://github.com/stefan750> @Olrosse<https://github.com/Olrosse> @Please-Pick-a-Name<https://github.com/Please-Pick-a-Name> @vulcan-dev<https://github.com/vulcan-dev> @StanleyDudek<https://github.com/StanleyDudek> @scisdev<https://github.com/scisdev> @O1LER<https://github.com/O1LER> @Anonymous-275<https://github.com/Anonymous-275> @Mack29446<https://github.com/Mack29446> @prestonelam2003<https://github.com/prestonelam2003> @50thomatoes50<https://github.com/50thomatoes50> @2PXL<https://github.com/2PXL> @AlexITA1100<https://github.com/AlexITA1100> @0R3Z<https://github.com/0R3Z> @Desoroxxx<https://github.com/Desoroxxx> @YumiNee213<https://github.com/YumiNee213> @JamesBlad<https://github.com/JamesBlad> @iTeeLion<https://github.com/iTeeLion> @ArmenG888<https://github.com/ArmenG888> @1eob<https://github.com/1eob> @jacobcargen<https://github.com/jacobcargen> @5TXdYWK<https://github.com/5TXdYWK> @daveywaveyHD<https://github.com/daveywaveyHD> @VanilleVaschnille<https://github.com/VanilleVaschnille> @rtkpX<https://github.com/rtkpX> @NewZulund<https://github.com/NewZulund> @Neptnium<https://github.com/Neptnium> @x0xDJSx0x<https://github.com/x0xDJSx0x> @NicholasMcMillan03<https://github.com/NicholasMcMillan03>,

We're changing the license of this codebase to AGPL-3.0.

Please respond with a short "Okay" or similar message of acknowledgement. If you have any issues or concerns, please make them known.

We will move ahead with the AGPL-3.0 change, we need to know who's code we need to remove for this.

**Comment by JamesBlad** [comment]
Okey, thx for informing. What is the reason for the change?

__________
JamesBlad

**Comment by OfficialLambdax** [comment]
For all my contributions, be it code or review, on all repositories that BeamMP owns i here by grant my okay

**Comment by StanleyDudek** [comment]
OK

**Comment by Please-Pick-a-Name** [comment]
what are the changes from the new licenses? and why?
i would probably say okay anyways but itd be nice to know

Lion ***@***.***>于2024年1月13日 周六15:41写道：

**Comment by 2PXL** [comment]
okay

**Comment by 0R3Z** [comment]
Okay

**Comment by rtkpX** [comment]
ª, Ok

**Comment by ArmenG888** [comment]
Okay

**Comment by O1LER** [comment]
Okay

**Comment by Olrosse** [comment]
Okay

**Comment by NicholasMcMillan03** [comment]
👍

**Comment by jacobcargen** [comment]
Okay

**Comment by 1eob** [comment]
Since i got emailed

Yes im happy with that
________________________________
From: Lion ***@***.***>
Sent: Saturday 13 January 2024 20:41
To: BeamMP/BeamMP ***@***.***>
Cc: Leo ***@***.***>; Mention ***@***.***>
Subject: [BeamMP/BeamMP] IMPORTANT LICENSE CHANGE (Issue #490)


Hey @Starystars67<https://github.com/Starystars67> @20dka<https://github.com/20dka> @snepsnepsnep<https://github.com/snepsnepsnep> @jojos38<https://github.com/jojos38> @OfficialLambdax<https://github.com/OfficialLambdax> @stefan750<https://github.com/stefan750> @Olrosse<https://github.com/Olrosse> @Please-Pick-a-Name<https://github.com/Please-Pick-a-Name> @vulcan-dev<https://github.com/vulcan-dev> @StanleyDudek<https://github.com/StanleyDudek> @scisdev<https://github.com/scisdev> @O1LER<https://github.com/O1LER> @Anonymous-275<https://github.com/Anonymous-275> @Mack29446<https://github.com/Mack29446> @prestonelam2003<https://github.com/prestonelam2003> @50thomatoes50<https://github.com/50thomatoes50> @2PXL<https://github.com/2PXL> @AlexITA1100<https://github.com/AlexITA1100> @0R3Z<https://github.com/0R3Z> @Desoroxxx<https://github.com/Desoroxxx> @YumiNee213<https://github.com/YumiNee213> @JamesBlad<https://github.com/JamesBlad> @iTeeLion<https://github.com/iTeeLion> @ArmenG888<https://github.com/ArmenG888> @1eob<https://github.com/1eob> @jacobcargen<https://github.com/jacobcargen> @5TXdYWK<https://github.com/5TXdYWK> @daveywaveyHD<https://github.com/daveywaveyHD> @VanilleVaschnille<https://github.com/VanilleVaschnille> @rtkpX<https://github.com/rtkpX> @NewZulund<https://github.com/NewZulund> @Neptnium<https://github.com/Neptnium> @x0xDJSx0x<https://github.com/x0xDJSx0x> @NicholasMcMillan03<https://github.com/NicholasMcMillan03>,

We're changing the license of this codebase to AGPL-3.0.

Please respond with a short "Okay" or similar message of acknowledgement. If you have any issues or concerns, please make them known.

We will move ahead with the AGPL-3.0 change, we need to know who's code we need to remove for this.

**Comment by Anonymous-275** [comment]
Okay

**Comment by Mack29446** [comment]
Okay

**Comment by 50thomatoes50** [comment]
Okay

**Comment by lionkor** [comment]
The new license is AGPL-3.0. This is considered an open source license (the current one is not). The current license is a) not really something most of the contributors know or have agreed to formally, and b) is non-free (as in freedom). The GPL family of licenses are based on the fundamental idea of software freedom.

An explanation of the license in practical terms: https://www.gnu.org/licenses/why-affero-gpl.html

Practically, this is BeamMP moving to open source.

@jojos38 @JamesBlad @Please-Pick-a-Name

**Comment by lionkor** [comment]
Its based on GPL 3.0 which you can find more info about here: https://www.gnu.org/licenses/quick-guide-gplv3.html

**Comment by AlexITA1100** [comment]
Ok.

**Comment by jojos38** [comment]
> The new license is AGPL-3.0. This is considered an open source license (the current one is not). The current license is a) not really something most of the contributors know or have agreed to formally, and b) is non-free (as in freedom). The GPL family of licenses are based on the fundamental idea of software freedom.
> 
> An explanation of the license in practical terms: https://www.gnu.org/licenses/why-affero-gpl.html
> 
> Practically, this is BeamMP moving to open source.
> 
> @jojos38 @JamesBlad @Please-Pick-a-Name

Alright, okay for me then, thanks for the explanation

**Comment by stefan750** [comment]
Ok

**Comment by snepsnepsnep** [comment]
Okay

**Comment by daniel-w0** [comment]
Sounds good, go for it 👍

**Comment by 5TXdYWK** [comment]
Ok

**Comment by VanilleVaschnille** [comment]
ok

**Comment by Neptnium** [comment]
ok

**Comment by x0xDJSx0x** [comment]
Ok

**Comment by prestonelam2003** [comment]
I approve!

**Comment by YumiNee213** [comment]
ok sure 👍

**Comment by NewZulund** [comment]
Yep sure, I agree. I believe this is a fair change.

**Comment by Desoroxxx** [comment]
> This means YOUR CODE that you contributed, if it's still in the current codebase, will be relicensed under AGPL-3.0 and you formally agree to that by responding positively here.

I am okay with my contributions being relicensed.

This is a good move forward.

**Comment by Please-Pick-a-Name** [comment]
just in case yeah i’m okay with it

**Comment by daveywaveyHD** [comment]
Okay

**Comment by iTeeLion** [comment]
Ok

**Comment by Starystars67** [comment]
All good!

**Comment by OfficialLambdax** [comment]
Almost everyone approved. Thank you!
@20dka and @scisdev how about you two?

**Comment by 20dka** [comment]
All good with me!
Apologies for the delay

**Comment by OfficialLambdax** [comment]
Now that we have everyones agreement, we are finally moving forward changing the BeamMP Lua mods restrictive license to a open source AGPLicense! Thank you everyone again!

@scisdev We couldnt find a way to get into touch with you through other means, so we looked at each of your contributions from the year 2020 to remove them for this license change to take effect, but we found that none of your early project contributions are still present today (:

Everyone, have a nice one o/
