### ISSUE TITLE
Change connect IP for public server

### ISSUE THREAD

**Issue by Epicminer256** [Starystars67/BeamNG-MP#594]
** Problem
I use ngrok, which works with direct connect. But when people connect from the server browser, it points to my actual public IP address (which is what I don't want)
** What would be nice
Have a section I can add in the config to point to a custom IP

**Comment by O1LER** [comment]
The beamMP backend always uses the IP that a server contacts the backend from, as the target for players to connect to.
Since tunneling services like CloudFlare or ngrok only route http/s traffic over their servers, but beamMP needs TCP and UDP, they wont work.

I think you mean by using ngrok in direct connect, that you are using the random ngrok subdomain in the connect field. Most definitely ngrok will just reroute that traffic to your actual IP, bypassing their tunnel, just like a regular DNS would do. You can rent a domain and have it point at your IP, same thing.

By creating a public server you accept that you are exposing parts of your network and infrastructure to, well, the public. Obfuscation is not a good risk mitigation, means that just because you are not giving away your actual IP easily, does not mean that theres no risk involved anymore. If you are uncomfortable exposing your network, take a look at our [partners that offer beamMP server hosting](https://docs.beammp.com/server/create-a-server/#disclaimer).

Also, im pretty sure that the exiting IP, the server that ends the tunnel and faces the public, will be chosen at random or by distance to the target IP by ngrok, so setting one custom IP wont do the trick. You would need to add all of ngroks IPs. They might use a different server, and thus outgoing IP, for every new connection.

Just a sidenote, this repo here is for the ingame mod that beamNG loads, the [server is here](https://github.com/BeamMP/BeamMP-Server)

**Comment by Gibus21250** [comment]
Hey! on worked on a IPv6 compatible server and client side. I have also added the possibility to custom the IP used by the server, wich it is now sended to beam mp backend.
This is the PR in question
https://github.com/BeamMP/BeamMP-Server/pull/359

This will correct your problem when it will be aprouved! i hope :)

**Comment by Starystars67** [comment]
> Hey! on worked on a IPv6 compatible server and client side. I have also added the possibility to custom the IP used by the server, wich it is now sended to beam mp backend. This is the PR in question [BeamMP/BeamMP-Server#359](https://github.com/BeamMP/BeamMP-Server/pull/359)
> 
> This will correct your problem when it will be aprouved! i hope :)

Hello, I am not sure how your PR addresses the specific issue at hand here. The issue here is that the user is attempting to use ngrok as a proxy which would not work for a BeamMP server due it it needing TCP and UDP access as  mentioned by O1LER above.

With regards to your PR though I notice that it has a conflict. Please can I ask that you address that and the comments on it. 😄 

I am closing this issue for now however due to the lack of response from OP.
